apiVersion: batch/v1
kind: Job
metadata:
  name: es-init-job
spec:
  template:
    spec:
      containers:
        - name: es-init
          image: curlimages/curl:8.6.0
          command:
            - sh
            - -c
            - |
              echo "Aguardando Elasticsearch..."
              until curl -s http://elasticsearch:9200; do sleep 5; done
              echo "Criando índice..."
              curl -X DELETE "http://elasticsearch:9200/game-of-life-requests"
              curl -X PUT "http://elasticsearch:9200/game-of-life-requests" \
                -H 'Content-Type: application/json' \
                -d '{
                  "mappings": {
                    "properties": {
                      "request_id": {"type": "keyword"},
                      "client_id": {"type": "keyword"},
                      "engine": {"type": "keyword"},
                      "powmin": {"type": "integer"},
                      "powmax": {"type": "integer"},
                      "start_time": {"type": "date"},
                      "end_time": {"type": "date"},
                      "duration_ms": {"type": "float"},
                      "status": {"type": "keyword"},
                      "error_message": {"type": "text"},
                      "num_generations": {"type": "integer"},
                      "board_size": {"type": "integer"},
                      "num_clients_active": {"type": "integer"},
                      "host_node": {"type": "keyword"},
                      "timestamp": {"type": "date"}
                    }
                  }
                }'
      restartPolicy: OnFailure
